### ISSUE TITLE
Investigate Electron 11 migration

### ISSUE THREAD

**Issue by warpdesign** [warpdesign/react-explorer#170]
Supporting Apple Silicon needs Electron 11.

Migrating first to Electron 8 could be a good idea: #105.

**Comment by warpdesign** [comment]
Unfortunately, electron-builder [doesn't support](https://github.com/electron-userland/electron-builder/issues/5095) ARM64 builds for macOS.

Maybe we could check electron-packager?

**Comment by Anil8753** [comment]
Does electron-packager work?

**Comment by warpdesign** [comment]
I have no idea: I haven't used electron-packager. I guess it will be quickly fixed since new Apple Silicon Macs are just around the corner.

**Comment by warpdesign** [comment]
Fixed in #240
