### ISSUE TITLE
please help me to integrate react-explorer in my existing react-electron project

### ISSUE THREAD

**Issue by bestcoder0612** [warpdesign/react-explorer#222]
I've tried to integrate react-explorer in my existing react-electron project.
But I am not sure if it is possible to use the current react-explorer on my existing react-electron project.
Please help me!
Thank you!

[react-electron.zip](https://github.com/warpdesign/react-explorer/files/6632767/react-electron.zip)

**Comment by warpdesign** [comment]
Could you add more details?

**Comment by warpdesign** [comment]
I'm closing this issue: feel free to reopen if you can provide more information.
