### ISSUE TITLE
No context menu on Linux!

### ISSUE THREAD

**Issue by jdev082** [warpdesign/react-explorer#235]
So, upon running the Linux Appimage. It appears no context menu shows up when right clicking an item. There isn't a context menu for Linux? I think its a bug.

**Comment by warpdesign** [comment]
Hi,
Unfortunately this is the expected behavior (and it's the same on Mac/Windows as well): there is no context menu for file/folder items. Most actions can be triggered using the main app menu or keyboard shortcuts.

**Comment by JaydenDev** [comment]
I myself have developed context menus for Electron based software. The ```electron-context-menu``` package provides a context menu (not without configuration though).

Once the package is installed import it.
```javascript
const ContextMenu = require("electron-context-menu");
```

Here's an example directly from the project I used the package with:
[Click Here](https://github.com/JaydenDev/Ink-Desktop/blob/master/main/main.js#L9)
