### ISSUE TITLE
These items should be hidden on Linux.

### ISSUE THREAD

**Issue by jdev082** [warpdesign/react-explorer#236]
These should be hidden:
![image](https://user-images.githubusercontent.com/92550746/173372258-2d09c7c6-1dd3-4645-b725-1939700452b8.png)

1. [Swap] isn't even a readable directory, it's the swap partition. The swap partition is basically extra emergency RAM, similar to the pagefile on Windows. As this doesn't even contain files, not even readable ones. This should be hidden.
2. EFI System Partition, The partition that is critical and makes the OS boot. Not only can this not be read, unless the FM is ran as root. It's also pretty useless to be there. And may make the user think its a bug. Since It can't be viewed, maybe a warning that the user doesn't have the permissions to access the directory?

**Comment by warpdesign** [comment]
I knew this wasn't perfect, but I didn't try it on Linux: it's really a bad experience: I'll try to improve that.

**Comment by warpdesign** [comment]
I installed MX Linux but don't see the ` [SWAP]`  partition: could you tell me the partition type you used for the swap so that I can reproduce & fix the problem?

**Comment by warpdesign** [comment]
Fixed in #329
